apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deploy
  namespace: 7shifts
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: container1
  template:
    metadata:
      labels:
        k8s-app: container1
    spec:
      containers:
      - name: container1
        image: leafarlins/7shifts:c1-v1.0
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /index.html
            port: 80
          timeoutSeconds: 2
          failureThreshold: 2
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            memory: 10Mi
            cpu: 20m
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  namespace: 7shifts
  name: container1-service
spec:
  selector:
    k8s-app: container1
  ports:
    - name: web
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: container1-ingress
  namespace: 7shifts
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    k8s-app: container1
spec:
  rules:
  - host: container1.7shifts
    http:
      paths:
      - backend:
          service:
            name: container1-service
            port:
              name: web
        path: /
        pathType: Prefix
