apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: container1-scaler
  namespace: 7shifts
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: container1-deploy
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: container2-scaler
  namespace: 7shifts
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: container2-deploy
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
