FROM nginx:1.7.9
COPY index.html /usr/share/nginx/html/index.html
COPY estilo.css /usr/share/nginx/html/estilo.css
COPY default.conf /etc/nginx/conf.d/default.conf
#RUN rm /usr/share/nginx/html/index.html
